config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    collection do
      post :confirm
    end
  end

  root 'sessions#new'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :favorites

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    mount_uploader :picture, PictureUploader
    validates :name, presence: true, length: { minimum: 10, maximum: 63206 }
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    mount_uploader :profile, ProfileUploader
    validates :username, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
    has_secure_password
    has_many :posts, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorite_posts, through: :favorites, source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end
    
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

    def index
        @user = current_user
        @posts = @user.favorite_posts
        @favorite = current_user.favorites.all
    end

    def create
        favorite = current_user.favorites.create(post_id: params[:post_id])
        redirect_to post_path(params[:post_id]), notice: "post registered as a favorite"
    end

    def destroy
        favorite = current_user.favorites.find_by(id: params[:id]).destroy
        redirect_to posts_path, notice: "post remove from favorite"
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @posts = Post.all
    end


    def show
        @favorite = current_user.favorites.find_by(post_id: @post.id)
    end


    def new
        @post = Post.new
    end


    def edit

    end


    def create
        @post = Post.new(post_params)
        @post.user = current_user
        if params[:back]
            render :new
        else
            if @post.save
                PostmailerMailer.post_send_mail(@post.user).deliver
                flash[:notice] = "Congratulations! You are post is successfully created!"
                redirect_to @post
            else
                render 'new'
            end
        end
    end

    def update
        if @post.update(post_params)
            flash[:notice] = "Congratulations! You are post is successfully Edited!"
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        if @post.destroy
            flash[:notice] = "Congratulations! You are post is successfully Deleted!"
            redirect_to posts_path
        end
    end

    def confirm
        @post = Post.new(post_params)
        @post.user = current_user
        render :new if @post.invalid?
    end

    private

    def set_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:name, :picture, :picture_cache, :user_id)
    end

    def require_same_user
        if current_user != @post.user
            flash[:alert] = "You can't delete or edit other users' data!"
            redirect_to @post
        end
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        if logged_in?
            redirect_to posts_path
            flash[:alert] = "You are already Logged In!"
          end
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Congratulations! Logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "There is something wrong with you own email or password!"
            render 'new'
       end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out successfully!"
        redirect_to root_path
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:new, :create]
    before_action :require_same_user, only: [:edit, :update, :destroy]
  
    def index
      @users = User.all
    end
  
    def show
      @posts = @user.posts
    end
  
    def new
      @user = User.new
    end
  
    def edit
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Welcome #{@user.username}, from my blog you have successfully signed up! Congratulations!"
        redirect_to @user
      else
        render 'new'
      end
    end
  
    def update
      if @user.update(user_params)
        flash[:notice] = "Successfully updated your account infromation!"
        redirect_to @user
      else
        render 'edit'
      end
    end
  
    def destroy
      @user.destroy
      session[:user_id] = nil
      flash[:notice] = "Successfully deleted your account and all associated posts"
      redirect_to root_path
    end
  
    private
  
    def user_params
      params.require(:user).permit(:username, :profile, :profile_cache, :email, :password)
    end
  
    def set_user
      @user = User.find(params[:id])
    end
  
    def require_same_user
      if current_user != @user
        flash[:alert] = "You can't edit other users' data"
        redirect_to @user
      end
    end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

    def choose_new_or_edit_post
        if action_name == 'new' || action_name == 'create'
          confirm_posts_path
        elsif action_name == 'edit'
          post_path
        end
    end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favoritepost.html.erb
  <% @posts.each do |post| %>
          <div class="card-body bg-white" style="width: 40rem;">
          <p class="card-text my-text text-left"><%= link_to post.user.username, user_path(post.user) %></p>
            <p class="card-text text-left"><%= post.name %></p>
            <p class="card-text text-center"><%= image_tag(post.picture.url, size: "570x300") if post.picture? %></p>
            <%= link_to 'View', post_path(post), class: "btn btn-outline-info px-4" %>
            <% if logged_in? && post.user == current_user %>
              <%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-primary px-4" %>
              <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure?" },
              class: "btn btn-outline-danger px-4" %>
            <% end %>
          </div>
          <div class="card-footer text-muted bg-white" style="width: 40rem;">
            <small>Created <%= time_ago_in_words(post.created_at) %> ago,
            edited <%= time_ago_in_words(post.updated_at) %> ago</small>
          </div>
  <% end %>

app/views/favorites/_favoriteposts.html.erb
<div class="container">
  <% @posts.each do |post| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <div class="card text-center shadow-sm p-3">
          <div class="card-header bg-white text-left text-primary font-weight-bold">
            <h5><%= link_to post.user.username, user_path(post.user) %></h5>
          </div>
          <div class="card-body">
            <p class="card-text text-left"><%= post.name %></p>
            <p class="card-text text-center"><%= image_tag(post.picture.url, size: "570x300") if post.picture? %></p>
            <%= link_to 'View', post_path(post), class: "btn btn-outline-info px-4" %>
            <% if logged_in? && post.user == current_user %>
              <%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-primary px-4" %>
              <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure?" },
              class: "btn btn-outline-danger px-4" %>
            <% end %>
          </div>
          <div class="card-footer text-muted bg-white">
            <small>Created <%= time_ago_in_words(post.created_at) %> ago,
            edited <%= time_ago_in_words(post.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/favorites/index.html.erb
<%= render 'shared/navigation' %>
<%= render 'shared/messages' %>

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-3">
            <div class="card-body">
                <div class="card-text text-center"><%= render 'favoritepost' %></div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <footer>
        <p>© 2020 INSTAGRAM FROM FACEBOOK</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
 
<div class="container mt-5">
  <%= form_with(model: @post, local: true, url: choose_new_or_edit_post) do |f| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <%= render 'shared/errors', obj: @post %>
        <div class="card text-center">
          <div class="card-header bg-grey text-center font-weight-bold my-font-size">
            <p><%= post %></p>
          </div>

          <div class="card-body" style="height: 27rem;">

            <p class="card-text text-center">
              <%= f.text_area :name, rows: "14", autofocus: true,
              class: "form-control", placeholder: "What's on your mind? #{current_user.username}" %>
            </p>

            <p class="card-text text-left">
              <%= f.file_field :picture %>
              <%= f.hidden_field :picture_cache %>
            </p>

          </div>

          <div class="card-footer">
            <p>
              <%= f.submit "#{name}", class: "btn btn-primary text-white btn-lg btn-block login-text" %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="container">
  <% @posts.each do |post| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <div class="card text-center shadow-sm p-3" style="width: 50rem;">
          <div class="card-header bg-white text-left text-primary font-weight-bold">
            <h5><%= link_to post.user.username, user_path(post.user) %></h5>
          </div>
          <div class="card-body">
            <p class="card-text text-left"><%= post.name %></p>
            <p class="card-text text-center"><%= image_tag(post.picture.url, size: "570x300") if post.picture? %></p>
            <%= link_to 'View', post_path(post), class: "btn btn-outline-info px-4" %>
            <% if logged_in? && post.user == current_user %>
              <%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-primary px-4" %>
              <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure?" },
              class: "btn btn-outline-danger px-4" %>
            <% end %>
          </div>
          <div class="card-footer text-muted bg-white">
            <small>Created <%= time_ago_in_words(post.created_at) %> ago,
            edited <%= time_ago_in_words(post.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/confirm.html.erb
<div class="container">
  <%= form_with(model: @post, url: posts_path, local: true) do |f| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <%= render 'shared/errors', obj: @post %>
        <div class="card text-center">
          <div class="card-header bg-grey text-center font-weight-bold my-font-size">
            <p>Send with the following contents</p>
          </div>
          <div class="card-body" style="height: 25rem;">
            <%= f.hidden_field :name %>
            <p><%= @post.name %></p>
            <%= f.hidden_field :picture_cache %>
            <p class="card-text"><%= image_tag(@post.picture.url, size: "570x300") if @post.picture? %></p>
          </div>
          <div class="card-footer">
            <p>
              <%= f.submit "Register", class: "btn btn-outline-primary px-4" %>
              <%= f.submit "Back", name:'back', class: "btn btn-outline-primary px-4" %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/confrim.html.erb
<div class="container">
  <%= form_with(model: @post, url: posts_path, local: true) do |f| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <%= render 'shared/errors', obj: @post %>
        <div class="card text-center">
          <div class="card-header bg-grey text-center font-weight-bold my-font-size">
            <p>Send with the following contents</p>
          </div>
          <div class="card-body" style="height: 25rem;">
            <%= f.hidden_field :name %>
            <p><%= @post.name %></p>
            <%= f.hidden_field :picture_cache %>
            <p class="card-text"><%= image_tag(@post.picture.url, size: "570x300") if @post.picture? %></p>
          </div>
          <div class="card-footer">
            <p>
              <%= f.submit "Register", class: "btn btn-outline-primary px-4" %>
              <%= f.submit "Back", name:'back', class: "btn btn-outline-primary px-4" %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/navigation' %>
<%= render 'form', post: "Edit Post", name: "Save" %>

app/views/posts/index.html.erb
<%= render 'shared/navigation' %>
<%= render 'shared/messages' %>
<h1 class="text-center mt-3 mb-2">Home Page</h1>
<%= render 'post' %>

app/views/posts/new.html.erb
 
<%= render 'shared/navigation' %>
<%= render 'form', post: "New Post", name: "Post" %>

app/views/posts/show.html.erb
<%= render 'shared/navigation' %>
<%= render 'shared/messages' %>

<div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <h1 class="text-center mt-0 mb-4">Post Details</h1>
        <div class="card text-center">
          <div class="card-header bg-white text-center text-primary font-weight-bold">
            <h4><%= link_to @post.user.username, user_path(@post.user) %></h4>
            <%= link_to image_tag(@post.user.profile.url, size: "120",class: "rounded-circle"), user_path(@post.user),class: "nav-link" %>
          </div>
          <div class="card-body">
            <div class="card-text text-center"><%= @post.name %></div>
            <div class="m-4"><%= image_tag(@post.picture.url, size: "570x300") if @post.picture? %></div>
            <% if @favorite.present? %>
              <%= link_to 'Remove from favorite', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-outline-danger' %>
            <% else %>
              <%= link_to 'Add to favorite', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-outline-primary' %>
            <% end %>
            <% if logged_in? && @post.user == current_user %>
              <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-outline-primary px-4" %>
              <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?" },
              class: "btn btn-outline-danger px-4" %>
            <% end %>
          </div>
          <div class="card-footer text-muted bg-white">
            <small>Created <%= time_ago_in_words(@post.created_at) %> ago,
            edited <%= time_ago_in_words(@post.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved!</h4>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
  <% end %>

app/views/shared/_messages.html.erb
<% if flash %>
   <% flash.each do |name, msg| %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
         <%= msg %>
         <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
         </button>
      </div>
   <% end %>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar sticky-top shadow-sm navbar-expand-md navbar-light bg-light">
  <%= link_to 'Instagram', posts_path, class: "nav-link my-text col-md-4" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse col-md-8" id="navbarNav">
      <div class="navbar-nav col-md-8">
        <div class="nav-item col-md-2">
          <%= link_to 'Users', users_path, class: "nav-link my-text" %>
        </div>
        <div class="nav-item col-md-2">
          <%= link_to 'Home', posts_path, class: "nav-link my-text" %>
        </div>
        <div class="nav-item col-md-3">
          <%= link_to 'Create Post', new_post_path, class: "nav-link my-text " %>
        </div>
        <div class="nav-item col-md-3">
          <%= link_to 'Favorite', favorites_path, class: "nav-link my-text " %>
        </div>
        <div class="nav-item col-md-3">
          <%= link_to 'MailInbox', letter_opener_web_path, target: '_blank', class: "nav-link my-text " %>
        </div>
      </div>
      <div class="navbar-nav col-md-5">
        <%= link_to image_tag(current_user.profile.url, size: "30", class: "rounded-circle nav-link my-text"), user_path(current_user) %>
        <%= link_to "#{current_user.username}", user_path(current_user), class: "nav-link my-text" %>
        <%= link_to 'Log Out', logout_path, class: "nav-link my-text", method: :delete %>
      </div>
  </div>
</nav>

app/views/users/_form.html.erb
 <div class="container mt-6">
    <%= form_with(model: @user, local: true) do |f| %>
        <div class="row justify-content-md-center">
            <div class="col-5 mt-6">
                <div class="card shadow text-center">
                    <div class="card-body", style="height: 450px;">
                        <p class="card-text text-left"><%= f.text_field:username,
                        class: "form-control shadow-sm py-4 mt-2", placeholder: "Enter a username"%></p>
                        <p class="card-text text-center"><%= f.email_field :email,
                        class: "form-control shadow-sm py-4 mb-4", placeholder: "Enter your email address" %></p>
                        <p class="card-text text-center"><%= f.password_field :password,
                        class: "form-control shadow-sm py-4 mb-4", placeholder: "Choose a password" %></p>
                        <p class="card-text text-left mt-4">
                            <%= f.label :upload_profile_picture, class: "badge badge-pill badge-secondary p-3",
                                        for: "upload-photo" %>
                            <%= f.hidden_field :profile_cache %>
                            <%= f.file_field :profile, id: "upload-photo" %>
                        </p>
                        <p>
                            <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary text-white btn-lg btn-block login-text" ) %>
                        </p>
                        <div class="card-footer">
                            <p class="text">
                                Do you have an account click Log In? <%= link_to 'Log In', login_path %>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/navigation' %>
<%= render 'shared/messages' %>
<%= render 'form' %>

app/views/users/index.html.erb
<%= render 'shared/navigation' %>
<%= render 'shared/messages' %>

<h1 class="text-center mt-4">Facebook Users</h1>
<div class="container">
  <% @users.each do |user| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <%= link_to user.username, user %>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <%= image_tag(user.profile.url, size: "90", class: "rounded-circle") if user.profile? %>
          </h5>
          <p class="card-text"><%= pluralize(user.posts.count, "posts") %></p>
          <%= link_to 'View profile', user, class: "btn btn-outline-success" %>
          <% if logged_in? and user == current_user %>
            <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-info" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/navigation' %>
<%= render 'shared/messages' %>
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
<div class= "d-flex justify-content-center">
    <%= image_tag(@user.profile.url, size: "150",class: "rounded-circle") if @user.profile? %>
</div>
    <% if logged_in? && @user == current_user %>
        <div class="text-center mt-4">
            <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
            <%= link_to "Delete Account", user_path(@user), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
        </div>
    <% end %>
<h3 class="text-center mt-4">Posts</h3>
<%= render 'posts/post' %>